/**
 * Sandboxed Lean runner. The only process that executes untrusted Lean code
 * (elaboration is code execution), so it runs as its own user with no
 * network and no database access — see the `lean-runner` systemd unit. Its
 * whole world is:
 *
 *   SPOOL/in   *.lean files written by the orchestrator (verifier.ts)
 *   SPOOL/out  *.json results it writes back
 *   WORK_DIR   scratch space
 *
 * For each check it (1) compiles the submission against the pinned Mathlib,
 * then (2) compiles a trusted audit wrapper that imports the result and
 * reports, for every declaration: its name, its exact pretty-printed
 * statement, and the axioms it depends on. The orchestrator turns that into
 * the verification outcome; this process decides nothing.
 */
import { mkdirSync, readdirSync, existsSync, rmSync, renameSync, writeFileSync, readFileSync, copyFileSync } from "node:fs";
import { join, basename } from "node:path";

const SPOOL = process.env.SPOOL_DIR ?? "/var/lib/lean-spool";
const SPOOL_IN = join(SPOOL, "in");
const SPOOL_OUT = join(SPOOL, "out");
const WORK_DIR = process.env.WORK_DIR ?? "/var/lib/lean-runner/work";
const LEAN_DIR = process.env.LEAN_DIR ?? "/srv/math-research/lean";
const READY = join(LEAN_DIR, ".ready");
const CONCURRENCY = Number(process.env.LEAN_CONCURRENCY ?? 2);
const TIMEOUT_MS = Number(process.env.LEAN_TIMEOUT_MS ?? 600_000);
const AUDIT_TIMEOUT_MS = 120_000;
const POLL_MS = 1_000;

/**
 * Environment (LEAN_PATH, toolchain PATH, …) captured by the project owner at
 * setup time via `lake env env > .env-cache`. Running lake here would need
 * git and ownership of the checkout — exactly what this sandbox must not
 * have — so we only ever read the cached snapshot.
 */
let leanEnv: Record<string, string> = {};

async function loadLeanEnv() {
  const cache = join(LEAN_DIR, ".env-cache");
  while (!existsSync(cache)) {
    console.log(`waiting for ${cache} (produced by lean setup)`);
    await Bun.sleep(15_000);
  }
  for (const line of readFileSync(cache, "utf8").split("\n")) {
    const eq = line.indexOf("=");
    if (eq > 0) leanEnv[line.slice(0, eq)] = line.slice(eq + 1);
  }
  if (!leanEnv.LEAN_PATH) throw new Error(".env-cache did not yield LEAN_PATH");

  // Libraries built outside the check project — MathlibPlus lives in its own
  // checkout with its own build tree. Appended rather than merged into
  // .env-cache, which is regenerated by `lake env env` and would lose it.
  const extra = process.env.EXTRA_LEAN_PATH;
  if (extra) {
    for (const dir of extra.split(":").filter(Boolean)) {
      if (!existsSync(dir)) throw new Error(`EXTRA_LEAN_PATH entry does not exist: ${dir}`);
    }
    leanEnv.LEAN_PATH = `${leanEnv.LEAN_PATH}:${extra}`;
    console.log(`extra LEAN_PATH: ${extra}`);
  }
}

// The audit reports every declaration the module added, and for each one the
// single fact that decides what a kernel pass is worth: is this declaration's
// *type* a proposition? `theorem foo : P` has type `P : Prop`, so the kernel
// checked a proof of P. `def Q : Prop := …` has type `Prop : Type`: it
// elaborates, it is a perfectly good formal statement, and it proves nothing.
// Only the kernel can tell those apart, so it is asked here rather than
// guessed later from a pretty-printed string.
function auditSource(moduleName: string): string {
  return `import ${moduleName}
open Lean Meta Elab Command in
run_cmd do
  let env \u2190 getEnv
  let some modIdx := env.getModuleIdx? \`${moduleName}
    | throwError "audited module not found"
  let mut count := 0
  for (name, info) in env.constants.toList do
    if env.getModuleIdxFor? name == some modIdx \u2227 !name.isInternal then
      if count \u2265 200 then break
      count := count + 1
      let (typeStr, axioms, isProof) \u2190 liftTermElabM do
        let fmt \u2190 Meta.ppExpr info.type
        let axs \u2190 collectAxioms name
        let prf \u2190 try Meta.isProp info.type catch _ => pure false
        return (fmt.pretty, axs, prf)
      let json := Json.mkObj [
        ("name", Json.str name.toString),
        ("type", Json.str typeStr),
        ("proof", Json.bool isProof),
        ("axioms", Json.arr (axioms.map (Json.str \u00b7.toString)))
      ]
      logInfo s!"AUDIT{json.compress}"
`;
}

type Decl = { name: string; type: string; axioms: string[]; proof?: boolean };

async function runLean(args: string[], cwd: string, timeoutMs: number, extraLeanPath?: string) {
  const env = { ...process.env, ...leanEnv };
  if (extraLeanPath) env.LEAN_PATH = `${env.LEAN_PATH}:${extraLeanPath}`;
  const proc = Bun.spawn(["lean", ...args], {
    cwd,
    stdout: "pipe",
    stderr: "pipe",
    timeout: timeoutMs,
    env,
  });
  const [exitCode, stdout, stderr] = await Promise.all([
    proc.exited,
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  // killed-by-timeout ends with a signal and no exit code; a fast nonzero
  // exit is an ordinary failure, not a timeout.
  return { exitCode, output: stdout + stderr, timedOut: proc.signalCode != null, signal: proc.signalCode };
}

async function runCheck(id: string) {
  const work = join(WORK_DIR, id);
  const moduleName = `Check${id}`;
  const result: Record<string, unknown> = { ok: false };
  try {
    mkdirSync(work, { recursive: true });
    // The sandbox mounts spool and work as separate bind mounts, so a rename
    // would fail with EXDEV — copy and unlink instead.
    copyFileSync(join(SPOOL_IN, `${id}.lean`), join(work, `${moduleName}.lean`));
    rmSync(join(SPOOL_IN, `${id}.lean`));

    const compile = await runLean(
      [`--root=${work}`, `-o`, join(work, `${moduleName}.olean`), join(work, `${moduleName}.lean`)],
      work,
      TIMEOUT_MS,
    );
    result.exit_code = compile.exitCode;
    result.timed_out = compile.timedOut;
    if (compile.signal) result.signal = compile.signal;
    result.output = compile.output.slice(-4000);
    // A compile that "succeeds" while reporting a sorry is not a pass.
    if (compile.exitCode === 0 && !compile.timedOut && !/declaration uses 'sorry'/.test(compile.output)) {
      result.ok = true;
      const auditFile = join(work, `Audit${id}.lean`);
      writeFileSync(auditFile, auditSource(moduleName));
      const audit = await runLean([`--root=${work}`, auditFile], work, AUDIT_TIMEOUT_MS, work);
      if (audit.exitCode === 0 && !audit.timedOut) {
        const decls: Decl[] = [];
        for (const match of audit.output.matchAll(/AUDIT(\{.*\})/g)) {
          try {
            decls.push(JSON.parse(match[1]!));
          } catch {
            /* skip unparsable line */
          }
        }
        result.audit_ok = decls.length > 0;
        result.decls = decls;
        // The audit ran and found nothing to report: the file declares no
        // theorems (`#check` on someone else's, an `example`, a bare import).
        // That is not an audit failure, and the caller should not be told the
        // audit broke.
        if (decls.length === 0) result.declares_nothing = true;
      } else {
        result.audit_ok = false;
        result.audit_error = audit.timedOut ? "audit timed out" : audit.output.slice(-2000);
      }
    }
  } catch (error) {
    result.audit_ok = false;
    result.audit_error = String(error);
  } finally {
    rmSync(work, { recursive: true, force: true });
    writeFileSync(join(SPOOL_OUT, `${id}.json.tmp`), JSON.stringify(result));
    renameSync(join(SPOOL_OUT, `${id}.json.tmp`), join(SPOOL_OUT, `${id}.json`));
  }
}

let running = 0;
const claimed = new Set<string>();

function tick() {
  if (!existsSync(READY)) return;
  for (const file of readdirSync(SPOOL_IN)) {
    if (running >= CONCURRENCY) break;
    if (!file.endsWith(".lean")) continue;
    const id = basename(file, ".lean");
    if (claimed.has(id)) continue;
    claimed.add(id);
    running++;
    runCheck(id)
      .catch((error) => console.error(`check ${id} crashed:`, error))
      .finally(() => {
        claimed.delete(id);
        running--;
      });
  }
}

mkdirSync(WORK_DIR, { recursive: true });
await loadLeanEnv();
console.log(`lean runner (sandboxed): spool=${SPOOL} work=${WORK_DIR} concurrency=${CONCURRENCY}`);
setInterval(tick, POLL_MS);
